#!/bin/sh

export DGP_DOMAINS=""               # INSERT YOUR OWN DOMAIN(S) HERE
export DGP_SECRET_KEY=""            # INSERT YOUR OWN DJANGO SECRET KEY HERE
export DGP_GOOGLE_OAUTH2_KEY=""     # INSERT YOUR OWN GOOGLE OAUTH2 KEY HERE
export DGP_GOOGLE_OAUTH2_SECRET=""  # INSERT YOUR OWN GOOGLE OAUTH2 SECRET HERE
